### ISSUE TITLE
Add Background Music.

### ISSUE THREAD

**Issue by shubhrai2811** [GDSC-IIIT-Kalyani/Typing-Speed-Test#6]
Currently, the game feels dull.
Add multiple music tracks to play in the background while typing.
also if possible add game sound effects.

**Comment by Kunalpal215** [comment]
Can you assign me this issue ?

**Comment by jatinverma14** [comment]
Can i work on this?

**Comment by savi001** [comment]
i am new to open source and so  interesed to work on it ,
ca u please assign to me.

**Comment by shubhrai2811** [comment]
@savi001  this would be a good first issue for you

**Comment by ppap1771** [comment]
if there is no update from the assignee assign me this issue.
